# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PromiseKitDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PromiseKitDemo
  pod 'PromiseKit'
  pod 'PromiseKit/CoreLocation'
  pod 'PromiseKit/CorePromise'
  pod 'PromiseKit/Foundation'

end
